#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.05

# PID gains
x_proportional_gain: 0.1
y_proportional_gain: 0.1
z_proportional_gain: 0.1
x_integral_gain: 0.0000005
y_integral_gain: 0.0000005
z_integral_gain: 0.0000005
x_derivative_gain: 0.000000001
y_derivative_gain: 0.000000001
z_derivative_gain: 0.000000001

angular_proportional_gain: 0.05
angular_integral_gain: 0.000
angular_derivative_gain: 0.0